@startuml

[*] --> created
created: New Payment
created: ExecutionContext
created: state: Created

created --> processing
processing: Payment processing
processing: ExecutionContext
processing: state: Processing
processing: taskId: "string"

processing --> delayed
delayed: Processing is delayed until the moment of time
delayed: ExecutionContext
delayed: state: Delayed
delayed: postponedTo: "timestamp"
delayed --> processing : Changed by a new task

processing --> suspend
suspend: Processing is suspend until the cause is resolved
suspend: ExecutionContext
suspend: state: Suspend
suspend: cause: "string"
suspend --> processing : Changed by a new task

processing --> finished
finished: Processing completed successfully
finished: ExecutionContext
finished: state: Finished
finished: payedAt: "timestamp"
finished --> [*]

@enduml